### ISSUE TITLE
Suggestion about deprecated vSemaphoreCreateBinary

### ISSUE THREAD

**Issue by bytesontherocks** [grygorek/FreeRTOS_cpp11#18]
This is just a suggestion. 
As "vSemaphoreCreateBinary()" is deprecated it can be replaced by "xSemaphoreCreateBinary()" but requires freeing the semaphore after created (https://www.freertos.org/FreeRTOS_Support_Forum_Archive/November_2013/freertos_Change_vSemaphoreCreateBinary_to_xSemaphoreCreateBinary_43ffda80j.html)

In condition_variable.h instead of using:

  semaphore()
  {
    vSemaphoreCreateBinary(_xSemaphore);
    if (!_xSemaphore)
      std::__throw_system_error(12); // POSIX error: no memory
  }

do:
  semaphore()
  {
  _xSemaphore = xSemaphoreCreateBinary();
  if (!_xSemaphore)
      std::__throw_system_error(12); // POSIX error: no memory
  else
      xSemaphoreGive(_xSemaphore);
  }

**Comment by grygorek** [comment]
Thanks for the feedback!
As this is not a bug Ill keep this issue open and fix it next time when working on it.
